# ==========================================
# Local Environment (Oracle 21c)
# ==========================================
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/xepdb1
spring.datasource.username=ivan
spring.datasource.password=1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# 增加 Hikari 連線池大小
spring.datasource.hikari.maximum-pool-size=200
# 延長等待連線的超時時間 (毫秒)
spring.datasource.hikari.connection-timeout=30000

#logging.level.com.portfolio=DEBUG

logging.level.com.portfolio=INFO

# 綠界測試環境 (MerchantID: 2000132)
ecpay.merchantId=2000132
ecpay.hashKey=5294y06JbCWpE5v5
ecpay.hashIv=v77hoKGq4kWxJtE1

ecpay.url=https://payment-stage.ecpay.com.tw/Cashier/AioCheckOut
ecpay.returnUrl=http://localhost:8084/portfolio/ecpay/callback
ecpay.orderResultUrl=http://localhost:8084/portfolio/pay-result

# 必須加上這一行，否則你的 RedisConfig 會失效
spring.redis.enabled=true
spring.redis.host=127.0.0.1
spring.redis.port=6379
spring.redis.database=0

# 這部分是給 RedisTemplate 用的，保留沒關係
spring.redis.lettuce.pool.max-active=200
spring.redis.lettuce.pool.max-wait=5000
spring.redis.timeout=5000ms

# =============================Kafka=========================================
# 1. 核心連線設定
spring.kafka.bootstrap-servers=localhost:9092

# 2. Producer (生產者) 設定
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3
spring.kafka.producer.properties.enable.idempotence=true

# 3. Consumer (消費者) 設定
spring.kafka.consumer.group-id=inventory-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.yourcompany.kafka.dto

spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
# 當發生反序列化錯誤時，將錯誤訊息包裝起來發送，避免無限重試
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
# 4. Listener (監聽器) 進階設定
spring.kafka.listener.ack-mode=RECORD
spring.kafka.listener.concurrency=3
# =============================Kafka=========================================