# ==========================================
# SIT Environment (Docker / Server)
# ==========================================
spring.datasource.url=jdbc:oracle:thin:@//oracle21c:1521/xepdb1
spring.datasource.username=system
spring.datasource.password=1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# SIT 環境建議關閉自動更新 Table 結構，避免誤刪資料
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false