# ==========================================
# Local Environment (Oracle 21c)
# ==========================================
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/xepdb1
spring.datasource.username=ivan
spring.datasource.password=1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# 增加 Hikari 連線池大小
spring.datasource.hikari.maximum-pool-size=200
# 延長等待連線的超時時間 (毫秒)
spring.datasource.hikari.connection-timeout=30000

logging.level.com.portfolio=DEBUG

# 綠界測試環境 (MerchantID: 2000132)
ecpay.merchantId=2000132
ecpay.hashKey=5294y06JbCWpE5v5
ecpay.hashIv=v77hoKGq4kWxJtE1

ecpay.url=https://payment-stage.ecpay.com.tw/Cashier/AioCheckOut
ecpay.returnUrl=http://localhost:8084/portfolio/ecpay/callback
ecpay.orderResultUrl=http://localhost:8084/portfolio/pay-result