# 通用設定
server.port=8084
server.servlet.context-path=/portfolio
server.servlet.encoding.charset=UTF-8

# Spring Messages & Thymeleaf
spring.messages.basename=base,errors
spring.messages.encoding=UTF-8
spring.mvc.hiddenmethod.filter.enabled=true
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

# JPA 通用設定
spring.jpa.database=ORACLE
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.hikari.connection-init-sql=ALTER SESSION SET TIME_ZONE='UTC'
server.forward-headers-strategy=native

# ==========================================
# 指定預設環境 (平常開發用 local)
# ==========================================
spring.profiles.active=local