-- 1. 建立商品表 (Product)
CREATE TABLE PRODUCT (
    ID NUMBER(19,0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    NAME VARCHAR2(255 CHAR),
    PRICE BINARY_DOUBLE,
    PRIMARY KEY (ID)
);

-- 2. 建立訂單紀錄表 (OrderRecord)
-- 注意：Oracle 中 "ORDER" 是保留字，建議表名使用 ORDER_RECORD
CREATE TABLE ORDER_RECORD (
    ID NUMBER(19,0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ORDER_ID VARCHAR2(255 CHAR),
    PRODUCT_ID NUMBER(19,0),
    AMOUNT BINARY_DOUBLE,
    STATUS VARCHAR2(50 CHAR),
    KAFKA_KEY VARCHAR2(255 CHAR),
    PRIMARY KEY (ID)
);

-- 3. 預先插入一些測試商品資料
INSERT INTO PRODUCT (NAME, PRICE) VALUES ('iPhone 15', 30000.0);
INSERT INTO PRODUCT (NAME, PRICE) VALUES ('MacBook Pro', 60000.0);
INSERT INTO PRODUCT (NAME, PRICE) VALUES ('AirPods', 5000.0);

COMMIT;


-- ===============================

CREATE TABLE ivan_txn_log (
    txn_id          VARCHAR(64) PRIMARY KEY, -- 交易唯一編號 (UUID 或 Snowflake ID)
    from_account    VARCHAR(20) NOT NULL,    -- 轉出帳號
    to_account      VARCHAR(20) NOT NULL,    -- 轉入帳號
    amount          DECIMAL(18, 2) NOT NULL, -- 交易金額
    currency        VARCHAR(3) DEFAULT 'TWD',-- 幣別
    status          VARCHAR(10),             -- 狀態: SUCCESS, FAIL, PROCESSING
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- 交易時間
    remark          VARCHAR(255)             -- 備註 (例如: "Redis-Lua Simulation")
);

-- 建立索引以利後續查詢
CREATE INDEX idx_txn_from ON ivan_txn_log(from_account);
CREATE INDEX idx_txn_to ON ivan_txn_log(to_account);
CREATE INDEX idx_txn_created ON ivan_txn_log(created_at);