services:
  # --- 新增 Oracle 資料庫服務 ---
  oracle21c:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle21c
    environment:
      - ORACLE_PWD=1234  # 請設定你的資料庫密碼
    ports:
      - "1522:1521"  # 如果你電腦本機也要連線才需要這行
    restart: always

  portfolio-app:
    build: .
    container_name: portfolio-app
    expose:
      - "8084"
    depends_on:
      - oracle21c  # 確保資料庫容器先啟動
    environment:
      # 這裡要告訴 Spring 去哪裡找資料庫
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle21c:1521/xepdb1
      - SPRING_DATASOURCE_USERNAME=system
      - SPRING_DATASOURCE_PASSWORD=1234
    restart: always

  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - portfolio-app
    restart: always